categories:
  - 'news'

postPages:
  layout: homepage
  layoutConfig:
    wrapPageInBox: false
    wrapTitleInBox: false
    includeTitle: false
    includeBreadcrumbs: false
  author: 'Casey Brooks'
  components:
    - type: 'pageContent'
      noWrapper: false

authors:
  - name: 'Casey Brooks'
    email: 'cjbrooks12@gmail.com'
