taxonomies:
  - key: category
    title: 'Categories'
    single: true
    setAsPageParent: true
    permalink: 'categories/:archiveIndex'
    includeFrom:
      - 'posts'
    orderBy:
      - 'publishDate'
    news:
      permalink: ':term/:archiveIndex'
  - key: tags
    title: 'Tags'
    single: false
    setAsPageParent: false
    permalink: 'tags/:archiveIndex'
    includeFrom:
      - 'posts'
    orderBy:
      - 'publishDate'
    news:
      permalink: ':term/:archiveIndex'

# Page configurations
termArchivePages:
  layoutConfig:
    wrapPageInBox: false
    wrapTitleInBox: false
    includeTitle: false
    includeBreadcrumbs: false

collectionArchives:
  - collectionType: 'kotlindoc'
    collectionId: 'modules-plugins'
    key: 'plugins'
    permalink: 'plugins/:archiveIndex'
  - collectionType: 'kotlindoc'
    collectionId: 'modules-themes'
    key: 'themes'
    permalink: 'themes/:archiveIndex'
  - collectionType: 'kotlindoc'
    collectionId: 'modules-bundles'
    key: 'bundles'
    permalink: 'bundles/:archiveIndex'
  - collectionType: 'pages'
    collectionId: 'showcase'
    permalink: 'showcase/:archiveIndex'
